opencodeiiita/Lets-Design-2.0

- Typography Task/shadaanhussain.txt
Issue: 1
Added figma file link in shadaanhussain.txt
-
-
-
> Added task link

- Typography Task/Palak-2109.txt
Issue: 1
Added google doc link in Typography Task.
-
-
-
> Added google doc link

- Typography Task/Tanushree-coder.txt
Issue: 1
added google doc link in Tanushree-coder.txt
> Created Tanushree-coder.txt

- Typography Task/adtoria.txt
Issue: 1
Added document link of my task to adtoria.txt
> Task 1: Added task link to a new file

- Typography Task/99anjali.txt
Issue: 1
Added a file 99anjali.txt
>  added a file

- Typography Task/rahulsingh-20.txt
Issue: 1
Added typography to the document and added the link to the doc.
> added link to doc file

- Typography Task/Ms-Error.txt
Issue: 1
Added Doc Link and Changed the Hierarcy Order Accordingly.
> Doc Link Added and Done Changes 

- Typography Task/codelord09
Issue: 1
Added a file codelord09
> Created file

- Typography Task/aashitachouhan.txt
> Typograpgy

- Typography Task/AgrimVerma.txt
Issue: 1
Added document link of my task to AgrimVerma.txt
-
-
-
> added txt file in Typography task

- Typography Task/MaqsudMallick.txt
Issue: 1
Added typography Task file as a Figma link 
> Added TypographyTask

- Typography Task/juhiechandra.txt
> #1 Adding file for this task

- Typography Task/Link_to_updated_text.md
Issue: 1
Created Link_to_updated_text.md and added the doc link.
> Added the link of the doc file.

- Typography Task/AKI35429.txt
Issue: 1
Typography Task and Granted Access.
-
-
-
> Typography Task Added

- Typography Task/raghavgoel25.txt
Issue: 1
Completed typography task and added link to doc in txt file
NIL
-
-
-
> Completed Typography task

- Typography Task/taniya-27.txt
Issue: 1
Added link for typography task in typography folder
> Typography task

- Design Rep - 3/Tanushree-coder.txt
> design rep-3

- Design Rep - 3/kaneki-ken260.txt
Issue: 276
Recreated the Cakes
> Design rep 3

- Design Rep - 4/Kirtee-tech.ai
Issue: 296
Added folder Design-Rep 4 and uploaded my file in it.
-
-
> Design Rep-4 task

- Design Rep - 4/Tanushree-coder.txt
Issue: 296
added figma link for design rep 4
> design-rep-4

- Design Rep - 4/shlesh.ai
> Did design rep 3

- Design Rep-4/kaneki-ken260.txt
> Design rep 4

- Design Rep - 5/diyawaghmare.txt
Issue: 308
Recreated flame design
-
-
-
> Design Rep 5

- Design Rep - 5/Tanushree-coder.txt
> design-rep-5

- Design Rep - 5/shlesh.ai
> Added Design rep 5

- Design Rep - 5/Revathi2306.txt
Issue: 308
Design Reps - Rep 5
> Design Reps - Rep 5

- The Final Task/diyawaghmare.txt
Issue: 331
Design thinking
-
-
-
> Final task

- The Final Task/schandu-eng/figma
> Added folder for Final task

- The Final Task/Tanushree-coder.txt
> final-task

- The Final Task/hotblooded058.txt
Issue: 331
created a design for open code
> the final task
